Property.Web/Controllers/OccupancyController.cs
using Microsoft.AspNetCore.Mvc;
using Property.Web.Services.Base;
using Property.Web.ViewModels;

namespace Property.Web.Controllers
{
    public class OccupancyController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        public OccupancyController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> Index()
        {
            var result = await unitOfWork.OccupancyService.GetAllAsync();
            return View(result.Record);
        }

        [HttpGet]
        public async Task<ActionResult> GetAll()
        {
            var response = await unitOfWork.OccupancyService.GetAllAsync();
            List<OccupancyVM> occ = new List<OccupancyVM>();
            foreach(var res in response.Record)
            {
                OccupancyVM occup = new OccupancyVM();
                occup.CustomerName = await GetNameById(res.CustomerId);
                occup.OwnerName = await GetNameById(res.OwnerId);
                occup.PropertyNumber = (await unitOfWork.PropertiesService.GetAsync(res.PropertyId)).Record.PropertyNumber;
                occup.OccupiedOn = res.OccupiedOn;
                occ.Add(occup);
            }

            return Json(new { data = occ });
        }
        
        private async Task<string> GetNameById(int id)
        {
            var result = await unitOfWork.RegistrationService.GetAsync(id);
            return result.Record.Name;
        }
    }
}

Property.Web/Controllers/PropertiesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Property.Web.Models;
using Property.Web.Services.Base;
using Property.Web.ViewModels;

namespace Property.Web.Controllers
{
    public class PropertiesController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        public PropertiesController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> Index()
        {
            var result = await unitOfWork.PropertiesService.GetAllAsync();
            return View(result.Record);
        }

        public async Task<IActionResult> LoadProperty()
        {
            var result = await unitOfWork.PropertiesService.GetAllAsync();
            return View(result.Record);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            PropertiesVM propertyView = new PropertiesVM();
            propertyView.Properties = new Properties();
            var result = await unitOfWork.RegistrationService.GetAllAsync();
            var ownerList = result.Record.Where(x=> x.Type == "Owner").ToList();
            List<SelectListItem> item = new List<SelectListItem>();
            foreach(var owner in ownerList)
            {
                SelectListItem lst = new SelectListItem();
                lst.Text = owner.Name;
                lst.Value = owner.Name;
                item.Add(lst);
            }
            propertyView.Owner = item;

            return View(propertyView);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Properties properties)
        {
            if (ModelState.IsValid)
            {
                var response = await unitOfWork.PropertiesService.AddAsync(properties);
                if (response.ResponseCode == System.Net.HttpStatusCode.Created)
                {
                    TempData["success"] = response.Message;
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["error"] = response.Message;
                    return View(properties);
                }
            }
            else
                return View(properties);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            else
            {
                var response = await unitOfWork.PropertiesService.GetAsync(id.Value);
                if (response.ResponseCode == System.Net.HttpStatusCode.Found)
                {
                    PropertiesVM propertyView = new PropertiesVM();
                    propertyView.Properties = response.Record;                
                   
                    var result = await unitOfWork.RegistrationService.GetAllAsync();
                    var ownerList = result.Record.Where(x => x.Type == "Owner").ToList();
                    List<SelectListItem> item = new List<SelectListItem>();
                    foreach (var owner in ownerList)
                    {
                        SelectListItem lst = new SelectListItem();
                        lst.Text = owner.Name;
                        lst.Value = owner.Name;
                        item.Add(lst);
                    }
                    propertyView.Owner = item;
                    return View("Create", propertyView);
                }
                else
                {
                    TempData["error"] = response.Message;
                    return NotFound();
                }
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Properties properties)
        {
            if (!ModelState.IsValid)
            {
                return View(properties);
            }
            var response = await unitOfWork.PropertiesService.UpdateAsync(properties);
            if (response.ResponseCode == System.Net.HttpStatusCode.OK)
            {
                TempData["success"] = response.Message;
                return RedirectToAction("Index");
            }
            else
            {
                TempData["error"] = response.Message;
                return View(properties);
            }
        }

        [HttpGet]
        public async Task<ActionResult> GetAll()
        {
            var response = await unitOfWork.PropertiesService.GetAllAsync();
            return Json(new { data = response.Record });
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var result = await unitOfWork.PropertiesService.GetAsync(id);
            if (result == null || result.Record == null)
            {
                return Json(new { success = false, message = result.Message });
            }
            var response = await unitOfWork.PropertiesService.DeleteAsync(id);
            if (response.ResponseCode == System.Net.HttpStatusCode.OK)
            {
                return Json(new { success = true, message = response.Message });
            }
            else
            {
                return Json(new { success = false, message = response.Message });
            }

        }
    }
}

Property.Web/Controllers/RegistrationController.cs
using Microsoft.AspNetCore.Mvc;
using Property.Web.Models;
using Property.Web.Services.Base;
using Property.Web.ViewModels;
using System.Net;

namespace Property.Web.Controllers
{
    public class RegistrationController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        public RegistrationController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> Index()
        {
            var result = await unitOfWork.RegistrationService.GetAllAsync();            
            return View(result.Record);
        }
        [HttpGet]
        public IActionResult Create()
        {
            RegistrationViewModel registrationView = new RegistrationViewModel();
            registrationView.Registration = new RegistrationModel();
            return View(registrationView);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RegistrationModel registration)
        {            
            if (ModelState.IsValid)
            {
                var response = await unitOfWork.RegistrationService.AddAsync(registration);
                if (response.ResponseCode == System.Net.HttpStatusCode.Created)
                {
                    TempData["success"] = response.Message;
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["error"] = response.Message;
                    return View(registration);
                }
            }
            else
                return View(registration);
        }
        
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            else
            {
                var response = await unitOfWork.RegistrationService.GetAsync(id.Value);
                if (response.ResponseCode == System.Net.HttpStatusCode.Found)
                {
                    //TempData["success"] = response.Message;
                    RegistrationViewModel registrationView = new RegistrationViewModel();
                    registrationView.Registration = response.Record;
                    return View("Create", registrationView);
                }
                else
                {
                    TempData["error"] = response.Message;
                    return NotFound();
                }
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(RegistrationModel registration)
        {
            if (!ModelState.IsValid)
            {
                return View(registration);
            }
            var response = await unitOfWork.RegistrationService.UpdateAsync(registration);
            if (response.ResponseCode == System.Net.HttpStatusCode.OK)
            {
                TempData["success"] = response.Message;
                return RedirectToAction("Index");
            }
            else
            {
                TempData["error"] = response.Message;
                return View(registration);
            }
        }

        [HttpGet]
        public async Task<ActionResult> GetAll()
        {
            var response = await unitOfWork.RegistrationService.GetAllAsync();
            return Json(new { data = response.Record });
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteRecord(int id)
        {
            var result = await unitOfWork.RegistrationService.GetAsync(id);
            if (result == null || result.Record == null)
            {
                return Json(new { success = false, message = result.Message });
            }
            var response = await unitOfWork.RegistrationService.DeleteAsync(id);
            if (response.ResponseCode == System.Net.HttpStatusCode.OK)
            {                
                return Json(new { success = true, message = response.Message });
            }
            else
            {
                return Json(new { success = false, message = response.Message });
            }

        }
    }
}

Property.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Property Service</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
    <script src="https://cdn.tiny.cloud/1/enjcwfsx5urxoutah6sdt1e2clxsrznr3mwf15dsc5ut98r2/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Property.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-danger border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Property Service</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Property Management</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item text-dark" asp-action="Index" asp-controller="Registration">Registration</a>                              
                                    <a class="dropdown-item text-dark" asp-action="Index" asp-controller="Properties">Property</a>                                    
                                </div>
                            </li>
                        }
                       
                        @if ((User.IsInRole("Customer")) || (User.IsInRole("Admin")))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Properties" asp-action="LoadProperty">Property</a>
                            </li>
                        }
                        
                        @if (User.IsInRole("Owner"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Properties" asp-action="Index">Property</a>                                
                            </li>
                        }
                        
                        @if (User.IsInRole("User") || User.IsInRole("Admin") || User.IsInRole("Owner") || User.IsInRole("Customer"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Occupancy" asp-action="Index">Occupancy</a>                                
                            </li>
                        }
                        
                        

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-danger">
        <div class="container">
            &copy; 2022 - EQ India 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

     <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Property.Web/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}